config/routes.rb
Rails.application.routes.draw do
  # get 'restaurants/index'
  # get 'restaurants/show'
  # get 'restaurants/new'
  # get 'restaurants/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    # resources :reviews, only: %i[new create]
    resources :reviews, only: %i[create]
  end

  # resources :reviews, only: %i[edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  CATEGORIES = %w[chinese italian japanese french belgian].freeze
  validates :category, presence: true, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true, length: { minimum: 1 }
  RATINGS = [0, 1, 2, 3, 4, 5].freeze
  validates :rating, presence: true, inclusion: { in: RATINGS }, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # before_action :set_review, only: [:edit, :update, :destroy]

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant

    if @review.save
      redirect_to @restaurant
    else
      # render :new
      render 'restaurants/show'
    end
  end

  # def edit
  # end

  # def update
  #   @review.update(review_params)

  #   redirect_to @review.restaurant
  # end

  # def destroy
  #   @review.destroy

  #   redirect_to @review.restaurant
  # end

  private

  # def set_review
  #   @review = Review.find(params[:id])
  # end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YelpMvp</title>
    <%# <meta name="viewport" content="width=device-width,initial-scale=1"> %>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-light bg-light mb-3 border-bottom">
      <%= link_to 'Restaurants', restaurants_path, class: 'navbar-brand' %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'New Restaurant', new_restaurant_path %>
        </li>
      </ul>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-secondary w-100' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit <%= @restaurant.name %></h1>

<%= render 'form', restaurant: @restaurant %>
<%= link_to 'Back', restaurants_path, class: 'btn btn-light w-100 mt-3 text-secondary border' %>

app/views/restaurants/index.html.erb
<%# <h1>Restaurants</h1>
<%= link_to '+ New', new_restaurant_path, class: 'btn btn-dark' %>
<%# <hr> %>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Category</th>
      <th scope="col" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.category %></td>
        <td>
          <%= link_to restaurant do %>
            <i class="far fa-eye"></i>
          <% end %>
        </td>
        <td>
          <%= link_to edit_restaurant_path(restaurant) do %>
            <i class="fas fa-pencil-alt"></i>
          <% end %>
        </td>
        <td>
          <%= link_to restaurant, method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="far fa-trash-alt"></i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>
<%= link_to 'Back', restaurants_path, class: 'btn btn-light w-100 mt-3 text-secondary border' %>

app/views/restaurants/show.html.erb
<h2>
  <%= @restaurant.name %>
</h2>

<%= link_to 'Back', restaurants_path, class: 'btn btn-dark mb-3' %>
<%= link_to 'Edit restaurant', edit_restaurant_path(@restaurant), class: 'btn btn-primary mb-3' %>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @restaurant.phone_number %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @restaurant.category %>
</p>

<%# <%= link_to "Add Review", new_restaurant_review_path(@restaurant), class: 'btn btn-primary mb-2' %>
<hr>

<h5>Leave a review</h5>
<%= render 'reviews/form', reivew: @review %>

<hr>

<h5>Reviews</h5>

<ul class="list-group mt-2">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item d-flex justify-content-between">
      <%= review.content %>
      <div>
        <% review.rating.times do %>
          <i class="fas fa-star"></i>
        <% end %>
      </div>
    </li>
  <% end %>
</ul>

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :rating, collection: Review::RATINGS %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/reviews/new.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :rating, collection: Review::RATINGS %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>